name: InventoryFilled
version: 1.2.1
description: A really small Minecraft Spigot Plugin to tell a player his inventory is full.
author: MCLovesMy
main: com.MCLovesMy.InventoryFilled
commands:
   inventoryfilled:
     description: The main InventoryFilled command.
     usage: /InventoryFilled
   if:
     description: The main InventoryFilled command.
     usage: /if
permissions:
  InventoryFilled.reload:
    description: User-friendly description
    default: op