  name: InventoryFilled
  version: 1.2.0
  description: A really small Minecraft Spigot Plugin to tell a player his inventory is full.
  author: MCLovesMy
  main: nl.MCLovesMy.Main
  commands:
     inventoryfilled:
       description: The main InventoryFilled command.
       usage: /InventoryFilled
     if:
       description: The main InventoryFilled command.
       usage: /if